language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
notifications:
  email: false
script:
  - npm run test
after_success:
  - npm run coverage
branches:
  only: master
  except: /^v\d+\.\d+\.\d+$/
